services:

  # MSSQL 
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_SA_PASSWORD}"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./packages/backend/scripts/init-db.sql:/init-db.sql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost",
             "-U", "sa", "-P", "${DB_SA_PASSWORD}",
             "-Q", "SELECT 1", "-No"]
      interval: 10s
      timeout: 5s
      retries: 10

  # BACKEND
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # FRONTEND
  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
      args:
        VITE_STRIPE_PUBLIC_KEY: "${VITE_STRIPE_PUBLIC_KEY}"
    container_name: frontend_build
    volumes:
      - frontend_dist:/usr/share/nginx/html

  # NGINX
  nginx:
    image: nginx:1.29-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  mssql_data:
  frontend_dist:
