name: ci

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - name: Enable Corepack
        run: corepack enable
      - name: Activate Yarn 4
        run: corepack prepare yarn@4.9.1 --activate
      - name: Install
        run: yarn install --immutable
      - name: Typecheck
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
